The authors would like to dispute the findings of the original review.

data.txt:
The reason for the project failing is mentioned as python not
recognizing the create_project() method call, this is elaborated as a
missing third party package problem.

The method call is present in the run_project.py python script that is
present in the project root (we also mention where to fnd it in the
build instructions). This was re-tested by us on the copy that was
sent to Dr.Collberg for the initial study, and works correctly.

A copy of our code is not available online, but we would be glad to
comply to any requests for them on a per demand basis.

Thank you for taking the time to perform this comprehensive review.
